### PR TITLE
Add GCP integration

### PR DESCRIPTION
**Pull request by seonaidm**
Integration resource enhancement to support connecting SignalFx to Google Cloud Platform (GCP).

### CODE REVIEW

**Comment by cory-signalfx** [comment]
Nice, taking a look now!

**Comment by seonaidm** [comment]
thanks @cory-signalfx, that's the rebase done.

**Comment by seonaidm** [comment]
Sorry, just noticed I forgot to mark the project credentials as sensitive, fixed now.

**Comment by cory-signalfx** [comment]
Excellent! Thanks so much @seonaidm!

**Pull request merged**
