### PR TITLE
issue-51 add timezone for time chart

### PR DESCRIPTION
**Pull request by zimingw**
A quick change to add timezone.  Have not tested with SignalFX though.

### CODE REVIEW

**Comment by cory-signalfx** [comment]
This looks legit. I'd like to hold off until I have merged #44, since I'm going to need to rewrite this patch to work in that world. ETA is either today or early next week.

**Comment by zimingw** [comment]
@cory-signalfx  Can I ask when this can be merged and released please?  I really like to this feature for my environment.
Thanks

**Comment by cory-signalfx** [comment]
I had scheduled this for next week, but I will work to get it integrated sooner, probably today!

**Comment by zimingw** [comment]
Hi Cory,
For point 1 and 2, did you mean you like to list the full list of options for timezone value, then add validation method similar to validateUnitTimeChart?  And update the unit test in *test.go?  
For point 3, I could not locate where timecharAPIToTF is, could you point me to the code file and line number please?

I am happy to do them once you can help me about point 3.
Regards
Ziming

**Comment by cory-signalfx** [comment]
Actually, I'll just merge this and make a followup PR that covers the things we need to add. I'm doing that because I realized in your 2 & 3 that you need to rebase for that to work.

I'll merge this and make another PR and cc you!

**Pull request merged**
