### PR TITLE
Correct docs for event overlays.

### LINKED ISSUE #26: Selected event overlay doesn't match event overlay
Dashboard can have `event_overlay` as well as `selected_event_overlay`, and the docs state they have same fields:

> `selected_event_overlay` - (Optional) Defines event overlays which are enabled by default. See `event_overlay` for a definition of fields.

However, unlike [`event_overlay`](https://github.com/signalfx/terraform-provider-signalfx/blob/12d56df44cf25bf97792e36f2881a88870c8af03/signalfx/dashboard.go#L288), [`selected_event_overlay`](https://github.com/signalfx/terraform-provider-signalfx/blob/12d56df44cf25bf97792e36f2881a88870c8af03/signalfx/dashboard.go#L351) lacks `line`, `label`, and `color` attributes.

### PR DESCRIPTION
**Pull request by cory-signalfx**
# Summary

Fixes busted docs for event overlays, which are confusingly wrong.

# Motivation

Fixes #26

### CODE REVIEW

**Comment by detouched** [comment]
Hm, the change you proposed doesn't match what I observed. I was able to use all parameters in `event_overlay`, but not in `selected_event_overlay`.

That said, this worked fine:
```
  event_overlay {
    signal = "Initialised lifecycle hook"
    label = "Started"
    color = "orange"
    line = true
    source {
      property = "service_id"
      values = ["some-service"]
    }
  }
```

However, when I tried to replace `event_overlay` with `selected_event_overlay` (because I wanted these to be enabled by default) I got errors:
```
Error: module.dashboards.signalfx_dashboard.some_service: selected_event_overlay.0: invalid or unknown key: color
Error: module.dashboards.signalfx_dashboard.some_service: selected_event_overlay.0: invalid or unknown key: label
Error: module.dashboards.signalfx_dashboard.some_service: selected_event_overlay.0: invalid or unknown key: line
```

So in fact `selected_event_overlay` currently **does not** support `color`, `label` or `line` properties.

I think it would make sense if both `event_overlay` and `selected_event_overlay` supported all parameters. It wouldn't hurt if color, style and label are predefined for a suggested overlay?

**Comment by cory-signalfx** [comment]
Hrm, ok. I made my change by reading the API docs and not looking at the schema. I see now that the schema is inverted from what I documented. How odd. Lemme look a bit closer at the code.

The API docs for SignalFx claim that the `event_overlay` only supports the things in `selected_event_overlay.sources`. If we're doing something else in the code, I need to reconcile those without breaking compat. :)

**Comment by detouched** [comment]
Cool, thanks!

> The API docs for SignalFx claim that the event_overlay only supports the things in `selected_event_overlay.sources`.

This makes sense to me: selected overlays allow UI options while suggested overlays only define the source.

**Comment by cory-signalfx** [comment]
Indeed, it made sense to me too. But I think it's actually inverted. I'm poking at the code for the API and will figure it out and report back with an adjusted PR. Thanks for looking, more soon!

**Comment by detouched** [comment]
Thanks for looking into this!

Btw, when I said `event_overlay` worked fine above, I also meant that UI options were as I expected them: the overlay has been created and has not been selected by default, but when I selected it manually in UI, it had all UI options applied as I configured (color, line style and label). So those are definitely supported by `event_overlay`.

**Comment by cory-signalfx** [comment]
Indeed. You've got it right. I think the problem is on my end. I think the docs — which I blindly reproduced in the docs patch here — are actually *inverted*.

This reminds me of before I worked at SignalFx and used this. I think the real way this works is you define all the `event_overlays` then just specify them on/off on `selected_event_overlays`. That jives with your outcome and what the docs used to be. So I think the actual solution here is that the docs go back with some improvements and our own API docs get a fix. (I'm checking on this internally and will likely know later today, since it's early on the west coast!)

**Comment by cory-signalfx** [comment]
I've adjusted the docs, but still need to do some work internally to verify they are correct.

**Comment by cory-signalfx** [comment]
Ok @detouched I think this is correct now. I will hold off on merging until next week cuz some folks here are out and I want to be doubly sure that this and the documentation bug are correct!

**Pull request merged**
